### PR TITLE
suppress warning for deprecated declaration

### PR DESCRIPTION
**Pull request by acerbetti**

### CODE REVIEW

**Comment by fabiocaccamo** [comment]
Why not just replacing ``kCLAuthorizationStatusAuthorizedAlways`` with ``kCLAuthorizationStatusAuthorizedAlways`` if system version >= 8 instead of suppress warning?

**Comment by acerbetti** [comment]
this is what your code is doing already, it checks for __IPHONE_OS_VERSION_MAX_ALLOWED > 8 and go for the other route anyway.

If you Xcode is old, corner case, it will return a compile error because it doesn't know about kCLAuthorizationStatusAuthorizedAlways

**Comment by fabiocaccamo** [comment]
Sorry, I forgot that I already done it :)

**Comment by fabiocaccamo** [comment]
Just pushed pod 1.1.11

**Comment by acerbetti** [comment]
thank you

**Pull request merged**
